# Generated by Django 6.1.1 on 2026-09-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
